lyraproj/lyra

cmd/lyra/cmd/apply.go
cmd/lyra/cmd/embedded.go
cmd/lyra/cmd/root.go
cmd/lyra/cmd/validate.go
cmd/lyra/cmd/version.go
cmd/lyra/ui/ui.go

Better help text

---

go.mod
go.sum

Pulls in PR https://github.com/lyraproj/servicesdk/pull/3 to correct the log level.

Pull latest of servicesdk (and others) for log level

---

cmd/goplugin-example/example/start.go
cmd/goplugin-example/resource/resource.go

Fixed up the example provider
Works with this gist https://gist.github.com/markfuller/5f3961de9d71293cbb57e4a9afabc4eb

Get example provider workable from workflow

---

3RDPARTY_LICENSES.txt
cmd/lyra/main.go
go.mod
go.sum

…in the stupidest possible way™
Signed-off-by: jdwelch <me@jdwelch.net>

adds support to run controller on GKE cluster

---

cmd/lyra/cmd/delete.go
cmd/lyra/cmd/root.go
cmd/lyra/ui/ui.go
locales/en_US/default.po
pkg/apply/apply.go

This commit adds the command `delete` and ensures that the current
`apply` command makes use of the garbage collector.
closes #45

(#45) Add delete command and calls to garbage collector

---

go.mod
go.sum

Follow servicesdk PR #14 allow time.Time to be serialized.

---

cmd/goplugin-aws/resource/iam_role.go
cmd/goplugin-aws/resource/instance.go
cmd/goplugin-aws/resource/instance_test.go
cmd/goplugin-aws/resource/internet_gateway.go
cmd/goplugin-aws/resource/keypair.go
cmd/goplugin-aws/resource/native_instance.go
cmd/goplugin-aws/resource/native_internet_gateway.go
cmd/goplugin-aws/resource/native_route_table.go
cmd/goplugin-aws/resource/native_security_group.go
cmd/goplugin-aws/resource/native_subnet.go
cmd/goplugin-aws/resource/native_vpc.go
cmd/goplugin-aws/resource/register_types.go
cmd/goplugin-aws/resource/register_types_test.go
cmd/goplugin-aws/resource/route_table.go
cmd/goplugin-aws/resource/security_group.go
cmd/goplugin-aws/resource/shared.go
cmd/goplugin-aws/resource/subnet.go
cmd/goplugin-aws/resource/vpc.go
plugins/aaws.pp
plugins/attach.pp
plugins/attachnative.pp
plugins/iamrole.pp

* Register various AWS SDK ("Native") types and customer handlers for them, example data (`attachnative.pp`)
* Add IamRole, RoleHandler and sample data (`iamrole.pp`) to create a role #40

Add IamRole, along with native implementations for various AWS types

---

plugins/attachterraformyaml.yaml

Adding an example of using the Terraform AWS provider in conjunction with the YAML parser.

Adding Workflow example using YAML and Terraform providers

---

docs/workflow-puppet-dsl.md
docs/workflow-semantics.md

Update the Workflow Semantics and Puppet Workflow DSL docs

(#82) Update workflow-semantics.md and workflow-puppet-dsl.md

---

pkg/apply/apply.go

Combines with https://github.com/lyraproj/lyra-operator/pull/3

Add deletion of workflow from k8s

---

go.mod
go.sum

Closes #78 (only updates the single mod because of an error encountered updating  k8s.io/api/admissionregistration/v1alpha1)

Update lyra-operator mod only

---

.travis.yml

Turn off make checklicenses

---

go.mod
go.sum

Follows https://github.com/lyraproj/puppet-workflow/pull/5 (Coerce state properties)

Update mods to follow https://github.com/lyraproj/puppet-workflow/pull/5

---

pkg/bridge/marshall.go
pkg/bridge/marshall_test.go

Add support for arrays in the TF provider marshal/unmarshal.

Marshal arrays in TF provider

---

docs/workflow-puppet-dsl.md
docs/workflow-semantics.md

This commit updates the documentation with respect to the changes
decided in #90.
- "action" => "stateHandler"
- "stateless" => "action"

Improve workflow activity terminology.

---

cmd/goplugin-tf-azurerm/generated/generated.go
cmd/goplugin-tf-github/generated/generated.go
cmd/goplugin-tf-google/generated/generated.go
cmd/goplugin-tf-kubernetes/generated/generated.go
go.sum
plugins/types/TerraformAzureRM.pp
plugins/types/TerraformGitHub.pp
plugins/types/TerraformGoogle.pp
plugins/types/TerraformKubernetes.pp

The AWS variant of the provider had update support but I didn't regenerate the others properly ...

Regenerate bridge providers to add update support

---

README.md

The README had gotten a little out of sync with reality.

Update Mid-March current status in README

---

Makefile

~~There are two commits here.~~
This commit changes the Makefile to check for all directories in `cmd` that fit the pattern `goplugin-*` and builds/lints each on the assumption it contains a plugin. That should avoid Makefile changes as we (or contributors) add future plugins.
It also adds a new `generate` target that runs the bridge generator, rebuilds, regenerates types and sanity checks everything.
~~The second commit is all the changes to generated stuff that fell out of the 1st commit :)~~
~~@thallgren I included TS generation here. Good move do you think? Most of that 2nd commit is TS types.~~

 Makefile support for content generation and build/lint plugins by wildcard

---

cmd/lyra/cmd/apply.go
cmd/lyra/cmd/controller.go
cmd/lyra/cmd/delete.go
cmd/lyra/cmd/root.go
go.mod
go.sum
pkg/apply/apply.go

Adds a DlvConfig that is parsed from the CLI option --dlv and makes it
available to the Lyra plugin Loader by passing it in the px.Context

Add --dlv <dlv configuration> CLI option

---

pkg/apply/apply.go

This commit installs a signal handler that is triggered when the lyra
process is killed using the kill command without a signal argument (it
sends SIGTERM by default) or if the user types CTRL-C (SIGINT). The
handler ensures that all plugins are cleaned up.
Closes #221

Ensure that plugins are cleaned up on SIGINT and SIGTERM.

---

go.mod
go.sum
workflows/foober_iter.yaml

This commit captures the latest changes related to activity iteration
in the servicesdk/wfe modules in a YAML example to give an example of
what it might look like when an iteration is defined there.

Add iteration YAML example

---

examples/ts-samples/package-lock.json
examples/ts-samples/package.json
examples/ts-samples/src/aws_ts.ts
examples/ts-samples/src/azure_ts.ts
examples/ts-samples/src/foobernetes_ts.ts
examples/ts-samples/src/github_ts.ts
examples/ts-samples/src/googlecloud_ts.ts
examples/ts-samples/src/kubernetes_ts.ts
examples/ts-samples/src/sample_ts.ts

Removes all code that was made redundant by lyraproj/ts-workflow#4.

Remove boilerplate code in TypeScript examples.

---

go.mod
go.sum
workflows/aws.yaml
workflows/azure.yaml
workflows/foober_iter.yaml
workflows/foobernetes.yaml
workflows/github.yaml
workflows/googlecloud.yaml
workflows/kubernetes.yaml
workflows/sample.yaml
workflows/sample_alias.yaml
workflows/sample_output_hash.yaml
workflows/terraform.yaml

Fix YAML examples with respect to new canonical syntax.

---

cmd/goplugin-heroku/helper/service.go
cmd/goplugin-heroku/heroku/start.go
cmd/goplugin-heroku/main.go
cmd/goplugin-heroku/resource/app.go
cmd/goplugin-heroku/resource/app_test.go
cmd/goplugin-heroku/resource/build.go
cmd/goplugin-heroku/resource/build_test.go
go.mod
go.sum
workflows/heroku.yaml

Added following:
* Heroku provider using `heroku-go/v5`
* Heroku App resource and tests
* Heorku Build resource and tests
* Heroku helper to create a shared heroku service object.

Add heroku provider and the app and build resources
