lyraproj/lyra

cmd/goplugin-aws/aws/start.go, cmd/goplugin-aws/resource/acceptance_test.go, cmd/goplugin-aws/resource/internet_gateway.go, cmd/goplugin-aws/resource/route_table.go, cmd/goplugin-aws/resource/shared.go, cmd/goplugin-aws/resource/subnet.go, cmd/goplugin-aws/resource/vpc.go
* Rename fields in AWS types away from golint preferred common initialisms to work better with evaluator (subnetId rather than subnetID)
* Register subnet type and handler
* Better error handling and logging of tagging logic.
=> Working VPC and Subnet Creation

3RDPARTY_LICENSES.txt, cmd/goplugin-aws/resource/instance.go, cmd/goplugin-aws/resource/internet_gateway.go, cmd/goplugin-aws/resource/keypair.go, cmd/goplugin-aws/resource/route_table.go, cmd/goplugin-aws/resource/shared.go, cmd/goplugin-aws/resource/subnet.go, cmd/goplugin-aws/resource/vpc.go, pkg/logger/logger.go
This commit ensures that hclog.DefaultOptions is configured, both for
lyra and its embedded plug-ins.
The commit also removes a global `log` variable since initialization
of it causes a premature instantiation of the Default logger which in
turn makes impossible to subsequently configure it. Changing the
DefaultOptions has no effect once the Default logger has been retrieved.
=> (GEN-154) Ensure that hclog.Default is configured and used.

cmd/goplugin-identity/identity/identity.go
This commit ensures that the file name given to the Identity service
Start method is correctly set in the created Identity instance.
=> (GEN-151) Fix broken Identity service

.travis.yml, Makefile
* This commit means that ```make all``` does not run ```make checklicenses```, meaning that checkout under $GOPATH is not necessary (unless updating dependencies)
* We continue to run ```make checklicenses``` in travis (now, explicitly) which does use the $GOPATH. 
* Error and exit when running either ```make checklicenses``` or ```make updatelicenses``` outside of $GOPATH
* Add explicit GO111MODULES=on/off where applicable.
=> Don't run checklicenses in make all

README.md, data.yaml, plugins/attach.pp
This commit fixes the AWS attach workflow in attach.pp to be correct (as well as idempotently for the configuration of Vpc, Subnet, InternetGateway and RouteTable).  It directs users to run the `sample` workflow in the `plugins\example.pp` file as this has no side affects (in terms of creation of real-world resources).  
It adds a data.yaml with aws tag information.
=> Fix the example/attach.

cmd/goplugin-identity/identity/identity.go
A mistake in the Identity.withDb function caused errors returned by
the provided function to disappear. This commit ensures that they are
propagated correctly.
=> (maint) Ensure that error from bolt DB is propagated correctly

Makefile
https://github.com/golang/go/issues/29278 means that we cannot support 1.11.3 or earlier without removing the go.sum explicitly.  This commit checks that `go version` returns 1.11.4 or later
=> Check for go v1.11.4 or later in makefile

pkg/apply/apply.go, pkg/apply/apply_test.go
Parse out keys like `aws.tags.created_by` to create a deep map, converts to eval.OrderedMap and passes them to hiera
Closes #76
=> Map incoming hiera data as dot-separated hierarchy

cmd/goplugin-tf-aws/generated/generated.go, cmd/goplugin-tf-azurerm/generated/generated.go, cmd/goplugin-tf-google/generated/generated.go, cmd/goplugin-tf-kubernetes/generated/generated.go, pkg/bridge/gen.go, pkg/bridge/marshall.go, pkg/bridge/marshall_test.go, plugins/aaa-terraform-aws.pp, plugins/aaa-terraform-google.pp, plugins/aaa-terraform-kubernetes.pp
Fixes to the bridge provider generator to support arrays of strings. Support for arrays of arbitrary types is not yet supported.
Remove unnecessary ID fields from nested generated types.
=> TF generation fixes for arrays/IDs

README.md, k8s/vpc-workflow.yaml, plugins/aws_vpc_yaml.yaml
This commit uses hiera data for aws tags in plugins/aws_vpc_yaml.yaml and populates that hiera data in k8s/vpc-workflow.yaml
=> Use hiera data for tags, and populate from k8s CRD

k8s/lyra_v1alpha1_workflow_crd.yaml, k8s/lyra_v1alpha1_workflow_sample.yaml
* Ensure that `kubectl get workflows` will return richer information by adding `additionalPrinterColumns` section to the CRD definition.
* Add validation on incoming properties to CRD (more as a placeholder to be optionally built on in future)
=> Follow https://github.com/lyraproj/lyra-operator/pull/4

3RDPARTY_LICENSES.txt, go.mod, go.sum, pkg/loader/loader.go, plugins/tsw-sample.ll
Adds ability to express plugins as '.ll' (Lyra Link) files containing
a command and an argument or array of arguments expressed as yaml. Both
the command and the arguments are subjected to environment expansion.
At present, this should be viewed as a quick and dirty fix to enable
lyra to start a nodejs executable with a file.
Relates to #42.
=> Add support for lyra link files

examples/ts-samples/.clang-format, examples/ts-samples/.gitignore, examples/ts-samples/package-lock.json, examples/ts-samples/package.json, examples/ts-samples/src/Aws.ts, examples/ts-samples/src/vpc_with_subnet.ts, examples/ts-samples/tsconfig.json, examples/ts-samples/tslint.json, plugins/ts-samples.ll, plugins/tsw-sample.ll
This commit adds a TypeScript example in the form of a NPM package. It
contains two TS files, the Aws.ts which is generated from a TypeSet and
vpc_with_subnet.ts which contains the actual workflow and also the
boiler plate code to start the plugin.
Relates to #42.
=> Add TypeScript example.

Makefile
Prior to this commit, `make` (all) would validate the go version is 11.4+and if not error with the message `must be running Go version 1.11.4 or later` (cref https://github.com/golang/go/issues/29278#issuecomment-447537558).  This commit adds that same validation to `make lyra` as this is commonly used instead of `make`.  As a result the check is done twice for `make` but this is very fast.
=> Check for go modules as part of make lyra as well as make all

go.mod, go.sum, pkg/loader/loader.go
This commit removes the pre-load of all types and changes the call to
LoadeManifest in the puppet-workflow plug-in to take an extra directory
argument (the root of where it should expect to find a 'types'
directory).
Closes #148
=> Rely on that puppet-workflow loads types on demand

.golangci.yml, Makefile, cmd/lyra/cmd/root.go, pkg/bridge/marshall.go, pkg/bridge/marshall_test.go, pkg/loader/fs.go, pkg/loader/loader.go
By default, we lint only pkg/... and cmd/lyra/... to keep memory consumption low enough to run on Travis.
Added a "make lint-all" target that runs on all packages.
The build breaks if lint is found and this commit also fixes the handful of lint errors found by default (but not those found by lint-all).
=> Switch to golangci-lint

.travis.yml, Makefile, go.sum
This commit mostly updates the Makefile to create one fast and one thorough version of our build.
The default "make" target is now a fast variant of our existing lint/test/build approach. It runs the fast version of the linter, runs tests without race checks and builds binaries without stripping or compressing them. This gives a quick default build but with decent test/lint coverage. This is the experience that a new user who runs a simple "make" will see.
The "all" make target performs the same lint/test/build steps but more thoroughly and hence quite a bit more slowly (approx 5 mins vs 1 min). The full set of lint checks are performed, the tests are run with race detection and the binaries are shrunk/compressed.
Travis will now perform a "make all" to ensure thorough checks on PRs.
The …
=> Fast default "make" target but thorough Travis build

Makefile
Without this, the build failed on `make lint` and `make test`
if you didn't explictly set GO111MODULE in your environment.
Since the test in the `check-mods` target sets the env var
inline, I assume it should be set here as well.
=> Add GO111MODULE=on to lint and test steps

cmd/lyra/cmd/root.go, go.mod, go.sum
This commit leverages a new addition to the "issue" package. By
calling issue.IncludeStacktrace() with a "true" argument, all
issue.Reported errors will be created with a stacktrace from
the point they were created. As a result, almost all errors
generated by the framework will be displayed with a stacktrace.
Closes #184
=> Enable stacktrace for issue.Reported when running with --debug

docs/workflow-yaml.md, workflows/sample_alias.yaml, workflows/sample_output_hash.yaml
* This commit corrects the attribute example in the yaml markdown document and remove non-relevant example, as well as adding a couple of minimal examples for aliasing and outputting a hash.
=> Add samples for alias, output hash; tidy docs

CONTRIBUTING.md
This commit updates CONTRIBUTING.md to replace the github
boilerplate with a bunch of project specific information.
Note the section on DCO is commented-out for now, awaiting
approval to actually enact it.
=> Update contribution guidelines with (much) more info

.travis.yml, Makefile, README.md, examples/ts-samples/package-lock.json, examples/ts-samples/package.json, examples/ts-samples/src/azure_virtual_machine_ts.ts, examples/ts-samples/src/github_repository_ts.ts, examples/ts-samples/src/google_compute_instance_ts.ts, examples/ts-samples/src/k8s_namespace_service_ts.ts, examples/ts-samples/src/sample_ts.ts, examples/ts-samples/src/types/Identity.ts, examples/ts-samples/src/types/TerraformAzureRM.ts, examples/ts-samples/src/types/TerraformGitHub.ts, examples/ts-samples/src/types/TerraformGoogle.ts, examples/ts-samples/src/types/TerraformKubernetes.ts, workflows/azure_virtual_machine_ts.ll, workflows/github_repository_ts.ll, workflows/google_compute_instance_ts.ll, workflows/k8s_namespace_service_ts.ll, workflows/sample_ts.ll
This commit adds a typescript example and a `smoke-test-ts` make target to run this.  To facilitate this, `make generate-ts` outputs TypeScript types to the `examples/ts-samples/src/types` and runs `npm install` to resolve dependencies and transpile TypeScript to JavaScript.
It also adds a k8s example in TypeScript.
=> Add typesript example, k8s ts, and smoke test

Makefile, examples/ts-samples/package-lock.json, examples/ts-samples/package.json
Fixes the npm/vulnerability warnings:
```
> ts-samples@0.0.0 compile /home/travis/gopath/src/github.com/lyraproj/lyra/examples/ts-samples
> tsc -p .
npm WARN ts-samples@0.0.0 No description
npm WARN ts-samples@0.0.0 No repository field.
added 307 packages from 161 contributors and audited 489 packages in 25.298s
found 1 moderate severity vulnerability
run `npm audit fix` to fix them, or `npm audit` for details
build/lyra apply sample_ts || (echo "Failed apply typescript sample $?"; exit 1)
```
=> Fix npm warnings and suppress some Makefile output

go.mod, go.sum, workflows/aws.yaml, workflows/foobernetes.yaml
A pcore type name must consist of one to many capitalized segments
separated by double colon.
Relates to lyraproj/lyra#226
=> Ensure that all typespace and type entries follow name convention

CONTRIBUTING.md
We got the sign-off (hah!) from the organization to use DCO.
Signed-off-by: Eric Sorenson <eric@puppet.com>
=> Adding DCO verbiage to Contribution guidelines

cmd/lyra/cmd/generate.go, pkg/apply/apply.go, pkg/generate/generate.go, pkg/util/command.go
This commit moves the signal handler and the top-level error recovery
into a utility function so that the same logic can be used by both
the apply/delete and the generate commands. This also makes it possible
to use the same cleanup for future commands.
Closes #134
=> Ensure that the generate command terminates all plugins

pkg/logger/logger.go
This commit will make the lyra executable include a stacktrace in
issue.Reported errors when debug logging is active.
=> Ensure that errors from lyra executable include stacktrace

Dockerfile, Makefile
Lyra's dockerfile was a bit out of date. It now builds
and installs. It's pushed up to docker hub so you can:
docker pull lyraproj/lyra:latest
docker run -it lyraproj/lyra:latest /bin/bash
Then inside the container
lyra apply foobernetes
This also adds a `make docker` target to the Makefile.
=> Updates to improve docker support

go.mod, go.sum, workflows/aws.yaml, workflows/aws_pp.pp, workflows/azure.yaml, workflows/azure_pp.pp, workflows/foober_iter.yaml, workflows/foobernetes.yaml, workflows/foobernetes_pp.pp, workflows/github.yaml, workflows/github_pp.pp, workflows/googlecloud.yaml, workflows/googlecloud_pp.pp, workflows/kubernetes.yaml, workflows/kubernetes_pp.pp, workflows/sample.yaml, workflows/sample2.pp, workflows/sample_alias.yaml, workflows/sample_alias_pp.pp, workflows/sample_output_hash.yaml, workflows/sample_pp.pp
Updates the examples with respect to removal of 'typespace' in Puppet
and YAML manifests and removal of 'type', 'state', and the top level key
of YAML manifests.
Closes #253
Closes #254
=> Update pp and yaml examples

.travis.yml, Makefile, README.md
Node.js (and TypeScript) is completely optional for lyra so `make` (default) should not fail.  This commit removes the `smoke-test-ts` from the default make target, continues to run that check in travis and notes in the readme how to run the TypeScript smoke tests
Closes #255
=> Default make target should not enforce node version

cmd/lyra/cmd/apply.go, cmd/lyra/cmd/controller.go, cmd/lyra/cmd/delete.go, cmd/lyra/cmd/generate.go, go.mod, go.sum, pkg/apply/apply.go
This commit removes the option to explicitly name a data file for
Hiera data in favor of using a Hiera configuration stored on disk
in the file 'hiera.yaml'. If no such file exists, Lyra will fall back
to Hiera default behavior and first look for a file called 'data.yaml'
and then for 'data/common.yaml'.
=> Switch to Hiera with full configuration capabilities

Dockerfile, Makefile
Use a different minimal container instead of golang:latest
for the runtime.
For Lyra to run inside a minimal Alpine container, it needs
to be built with special arguments. This change adds a
BUILDARGS variable, prepended to relevant build/test steps,
so that the new 'make docker-build' target runs successfully
without impacting native-host builds.
=> Support docker-based builds in the Makefile

.gitignore, .travis.yml, Makefile, go.sum
* Add new target `format` which runs `go fmt ./...` and errors if any files were changed
* Add new target `tidy` which runs `go mod tidy` and errors if any change to go.sum was made.
* Add new target `pre-commit` which runs these along with a lint (contributors can choose to add a pre-commit hook locally by adding `.git/hooks/pre-commit`)
* Run `format` and `tidy` in travis to fail a build in the event of any changes
* Change go.sum to be output of `go mod tidy` where go version is 1.12.5 (different from 1.11.5) 
Fixes #268
=> Error if fmt or tidy is not clean

Dockerfile
Amends the Dockerfile to follow #267 - tested running foobernetes on the docker container e.g.
```sh
/src/lyra # lyra apply foobernetes
▸ apply done: foobernetes
/src/lyra #```
=> Issue 267 - the types folder should live under the build folder

cmd/goplugin-terraform/main.go, cmd/goplugin-terraform/resource/configuration.go, cmd/goplugin-terraform/resource/configuration_test.go, cmd/goplugin-terraform/terraform/start.go, examples/go-samples/spewer/run.go, examples/go-samples/terraform_go/tfroot/azure.tf, go.mod, workflows/spewer.ll, workflows/terraform.yaml
This commit adds a Terraform::Config resource with a Read which always returns a new value, in order to force the (idempotent) Update to be called each time.  The output is returned as a map based on the `terraform output` command.  Update and Create to the resource both run `terraform init`, `terraform apply` and `terraform output` whilst Delete calls `terraform destroy`
=> Terraform config as a resource

cmd/goplugin-foobernetes/main.go
The call to `issue.IncludeStacktrace()` was in the wrong location and
therefor insensitive to the setting of "LYRA_LOG_LEVEL".
=> Fix faulty initialization of stacktrace dump in Foobernetes

cmd/goplugin-foobernetes/resource/loadbalancer.go, tests/expected/deployment.json, workflows/foober_iter.yaml, workflows/foobernetes.yaml, workflows/foobernetes_pp.pp
While debugging hiera lookups, I noticed that although
we had the load balancer policy as the single external
parameter to the workflows, it was neither defined in
the resource type nor used in the body of the workflows.
This commit adds it to the Foobernetes::Loadbalancer
struct, the test data, and the resource definitions
in the workflows themselves.
(NB foober_iter is not fixed in this commit, but it
no longer applies cleanly and I'm not sure we need to
keep it at all)
=> Update foobernetes examples to use 'policy' parameter
